### ISSUE TITLE
Missing block in dcp ident response

### ISSUE THREAD

**Issue by mika-eng** [TcHaxx/TcPnScanner#30]
Testing with a Siemens CPU 1517F and a large customer project (about 160 devices), the Plc did only send the dcp ident packets. Thats due to a missing block in the dcp ident response packet. After extending the response packet with a 'IP' block, everything worked flawlessly. This block contains an identifier 'IP not set' (1 byte) as well as 4 bytes IP address, 4 bytes subnetmask and 4 bytes gateway (everything with value 0 of course, as we did not receive any IP address yet).
Also the first block of the response packet (DeviceNameOfStation) needs a padding byte if the device name length is a odd number.

I don't know how to pull a request, so i wrote this issue. But i already fixed it.

It seems like this is an Plc related issue (or maybe also firmware related).

Beste Grüße, Michael ;)

**Comment by densogiaichned** [comment]
Servus Michael @mika-eng ,

thanks a lot for pointing out this issue!
I've implemented your suggestions and did a quick test, but this didn't work as expected.

Could you have a look on the changes, maybe i missed something.
Or, even better, raise a PR with your changes.
You'll have to fork this repository first, see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks

Best regards

**Comment by mika-eng** [comment]
Ok no problem. See pull request #40.
This version has been tested with several TIA projects (Siemens CPU 1517F and CPU 1518F) as well as an old classic CPU 317F.
